services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mysql'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=my-secret-pw'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
